number_of_icebuses: 1
icebus_0:
  number_of_motors: 8
  motor_ids: [0,1,2,3,4,5,6,7]
  motor_ids_global: [0,1,2,3,4,5,6,7]
  muscle_type: ["myoMuscle","myoBrick100","myoMuscle","myoBrick100","myoMuscle","myoBrick300","myoMuscle","unknown"]
  coeffs_force2displacement:
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
  coeffs_displacement2force:
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]
body_part:
  name: ["head","shoulder_left","shoulder_right"]
  motor_ids_global:
    - [0,1,2]
    - [3,4,5]
    - [6,7]